### ISSUE TITLE
Mistune 2.0.2 incompatible with nbconvert 6.4.5

### ISSUE THREAD

**Issue by makromag** [ismaildawoodjee/GreatEx#4]
Hello everyone, 
so while trying to install everything on my Windows machine, I ran into the following problem:
![image](https://user-images.githubusercontent.com/31708184/161204598-9973b494-ae33-4f71-bd40-2f5986864c0e.png)
Essentialy, the Versions of nbconvert and mistune used in the project are incompatible and therefore the installation cannot finish. I will try to use an older Version of mistune and see if that helps.

Greetings

**Comment by ismaildawoodjee** [comment]
Greetings, I have updated the `requirements.txt` file to use fixed dependency versions, and have also added a `pip-chill-requirements.txt` for installing only the parent dependencies. The last couple of commits ismaildawoodjee@f458231 and ismaildawoodjee@5424fd17 should fix this issue.
