### ISSUE TITLE
Backports wants to use gcc which is not available

### ISSUE THREAD

**Issue by GertL** [ismaildawoodjee/GreatEx#5]
Didn't build with the following error.
[Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects]

**Comment by ismaildawoodjee** [comment]
May I know your OS and Python3 version? I can run the setup successfully on a Debian machine, but the Windows setup (with Python3.11) is giving errors for me as well.

After some experimentation, I used Python3.8 and the setup ran successfully on Windows with no issues. If you are on a Windows machine, I would suggest you use Python3.8. 

Other than that, there was also a slight change in container naming where you need to change `$PROJECT_NAME'_airflow-webserver_1'` into `$PROJECT_NAME'-airflow-webserver-1'` in the `airflow_conn.ps1` file (only for the Windows setup)
